### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by junocomp** [Antevea/rusty_clevo_fan#7]
It fails to build cpuio

here's the log

```
Compiling cpuio v0.3.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cpuio-0.3.0/src/lib.rs:4:1
  |
4 | #![feature(llvm_asm, const_fn)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `cpuio`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Antevea** [comment]
Hello, @giovannicaligaris.
cpuio lib requires nightly Rust.

**Comment by Antevea** [comment]
I have updated README.md.

**Comment by junocomp** [comment]
Sorry for the delay. 

I now have nightly set as default and still getting an error

```
error[E0557]: feature has been removed
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cpuio-0.3.0/src/lib.rs:4:22
  |
4 | #![feature(llvm_asm, const_fn)]
  |                      ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
error: could not compile `cpuio`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by Antevea** [comment]
Hello, @giovannicaligaris! This is new problem with cpuio lib on fresh rust version(
cpuio repository has opened issue (1 june 2021) https://github.com/emk/toyos-rs/pull/9.
Wait for merge into master branch to fix this problem.

**Comment by junocomp** [comment]
Hi, thanks for the update.

I am running rustc 1.55.0-nightly (868c702d0 2021-06-30)
